<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useGameStore } from '@/stores/game'
import { technologies } from '@/data/project'
import { multiplayer, type MultiplayerEvent } from '@/services/multiplayer'
const router = useRouter(); const game = useGameStore(); const issues = game.projectProblems; const page = ref(0); const perPage = 3; const totalPages = Math.ceil(issues.length / perPage); const visibleIssues = computed(() => issues.slice(page.value * perPage, (page.value + 1) * perPage)); const completed = computed(() => Object.keys(game.issueSelections).length); const localReady = ref(false); const remoteReady = ref(false); let stop: (() => void) | undefined
function techName(id: string) { return technologies.find(technology => technology.id === id)?.name || id }
function requestPage(direction: number) { if ((direction < 0 && page.value === 0) || (direction > 0 && page.value === totalPages - 1)) return; if (!multiplayer.connected || !multiplayer.room) { page.value += direction; localReady.value = false; remoteReady.value = false; return } localReady.value = true; multiplayer.gameEvent('page-ready', { page: page.value, direction }); advancePage(direction) }
function advancePage(direction: number) { if (localReady.value && remoteReady.value) { page.value += direction; localReady.value = false; remoteReady.value = false } }
onMounted(() => { stop = multiplayer.on((event: MultiplayerEvent) => { if (event.type === 'game-event' && event.event === 'page-ready') { const payload = event.payload as { page:number; direction:number; playerId?:string }; if (payload.playerId === multiplayer.playerId) return; if (payload.page === page.value) { remoteReady.value = true; advancePage(payload.direction) } } }) })
onUnmounted(() => stop?.())
</script>
<template><div class="issues-stage"><header class="project-step-head"><span class="screen-kicker">ЭТАП 05 / 05 · INCIDENT ROOM</span><h1>Десять проблем.<br><em>Один шанс на запуск.</em></h1><p>Назначьте каждой проблеме технологическое решение из выбранного стека.</p></header><div class="issues-layout"><section class="issues-list"><article v-for="issue in visibleIssues" :key="issue.id" class="issue-card" :class="{ resolved: game.issueSelections[issue.id] }"><div class="issue-number">{{ String(issue.id).padStart(2,'0') }}</div><div class="issue-content"><div><span class="issue-category">{{ issue.category }}</span><b class="impact" :class="issue.impact">{{ issue.impact }}</b></div><h3>{{ issue.title }}</h3><p>{{ issue.detail }}</p><div class="issue-actions"><button v-for="tech in technologies.filter(item => issue.suggested.includes(item.id) || game.selectedTechIds.includes(item.id)).slice(0, 4)" :key="tech.id" :class="{ active: game.issueSelections[issue.id] === tech.id }" @click="game.solveIssue(issue.id, tech.id)">{{ tech.name }}</button></div></div><div class="resolved-mark">{{ game.issueSelections[issue.id] ? '✓' : '!' }}</div></article><div class="issue-pagination"><button class="btn secondary" :disabled="page === 0 || localReady" @click="requestPage(-1)">← Назад</button><span>{{ localReady ? 'ЖДЁМ ВТОРОГО ИГРОКА…' : `СТРАНИЦА ${page + 1} / ${totalPages}` }}</span><button class="btn secondary" :disabled="page === totalPages - 1 || localReady" @click="requestPage(1)">Далее →</button></div></section><aside class="incident-summary"><div class="summary-count"><span>РЕШЕНО</span><strong>{{ completed }}<small>/10</small></strong><div class="progress"><i :style="{width:`${completed*10}%`}"/></div></div><div class="chosen-stack"><span>ВАШ STACK</span><b v-for="id in game.selectedTechIds" :key="id">{{ techName(id) }}</b></div><button class="btn primary block" :disabled="completed < 10" @click="router.push('/roadmap')">СОБРАТЬ ROADMAP&nbsp; →</button></aside></div></div></template>
