<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { multiplayer, type MultiplayerEvent } from '@/services/multiplayer'

const router = useRouter(); const name = ref(localStorage.getItem('tech-lead-player-name') || 'Tech Lead'); const roomInput = ref(''); const room = ref(''); const playerOnline = ref(false); const ready = ref(false); const mode = ref<'duel'|'co-op'>('co-op'); const error = ref(''); const serverReady = ref(false)
let stop: (() => void) | undefined
function create() { error.value = ''; localStorage.setItem('tech-lead-player-name', name.value); multiplayer.lockedCandidates.clear(); if (!multiplayer.connect()) { error.value = 'Не задан адрес WebSocket-сервера. Проверьте .env и перезапустите Vite.'; return }; multiplayer.create(name.value) }
function join() { error.value = ''; localStorage.setItem('tech-lead-player-name', name.value); multiplayer.lockedCandidates.clear(); if (!multiplayer.connect()) { error.value = 'Не задан адрес WebSocket-сервера. Проверьте .env и перезапустите Vite.'; return }; multiplayer.join(roomInput.value, name.value) }
function handle(event: MultiplayerEvent) { if (event.type === 'room-created') { room.value = event.room; multiplayer.playerId = event.playerId; serverReady.value = true }; if (event.type === 'room-joined') { room.value = event.room; multiplayer.playerId = event.playerId; serverReady.value = true; playerOnline.value = true }; if (event.type === 'player-joined') playerOnline.value = true; if (event.type === 'player-left') playerOnline.value = false; if (event.type === 'error') error.value = event.message; if (event.type === 'mode-selected') mode.value = event.mode }
function toggleReady() { ready.value = !ready.value; multiplayer.ready(ready.value) }
async function copyRoom() { if (room.value) await navigator.clipboard?.writeText(room.value) }
function start() { multiplayer.selectMode(mode.value); router.push('/lobby') }
onMounted(() => { stop = multiplayer.on(handle) }); onUnmounted(() => stop?.())
</script>
<template><div class="multiplayer-screen"><header class="project-step-head"><span class="screen-kicker">MULTIPLAYER HUB · ONLINE</span><h1>Играйте вместе<br><em>в одной команде</em></h1><p>Создайте комнату для коллеги или подключитесь по коду.</p></header><div class="guest-auth"><div class="auth-avatar">{{ name.slice(0, 1).toUpperCase() }}</div><div><span>ГОСТЕВОЙ ПРОФИЛЬ</span><strong>{{ name || "Новый игрок" }}</strong><small>Без пароля · имя сохраняется на этом устройстве</small></div><b>● ONLINE</b></div><div v-if="!room" class="room-gate"><section class="room-card"><span class="room-label">СОЗДАТЬ НОВУЮ КОМНАТУ</span><h2>Пригласите второго техлида</h2><label>Ваше имя<input v-model="name" placeholder="Например, Алексей" /></label><button class="btn primary block" @click="create">СОЗДАТЬ КОМНАТУ&nbsp; →</button></section><div class="or-divider"><span>или</span></div><section class="room-card join-card"><span class="room-label">ПОДКЛЮЧИТЬСЯ</span><h2>У вас есть код?</h2><label>Код комнаты<input v-model="roomInput" maxlength="10" autocomplete="off" spellcheck="false" placeholder="ATLAS-3E3A" /></label><button class="btn secondary block" @click="join">ВОЙТИ В КОМНАТУ&nbsp; →</button></section></div><section v-else class="room-lobby"><div class="room-code"><span>КОД КОМНАТЫ</span><strong>{{ room }}</strong><button class="copy-room" @click="copyRoom">⧉ КОПИРОВАТЬ</button><small>Отправьте этот код второму игроку</small></div><div class="players-row"><div class="online-player"><i class="you"></i><span><b>{{ name }}</b><small>Вы · Tech Lead</small></span></div><div class="connection-line"><i :class="{ active: playerOnline }"></i><span>{{ playerOnline ? 'Синхронизировано' : 'Ждём второго игрока…' }}</span></div><div class="online-player" :class="{ waiting: !playerOnline }"><i></i><span><b>{{ playerOnline ? 'Второй игрок' : 'Свободное место' }}</b><small>{{ playerOnline ? 'Подключён' : 'Отправьте код комнаты' }}</small></span></div></div><div class="mode-select"><span>ВЫБЕРИТЕ ФОРМАТ</span><button :class="{ selected: mode === 'co-op' }" @click="mode='co-op'">🤝 <b>Совместная команда</b><small>Принимайте решения вместе</small></button><button :class="{ selected: mode === 'duel' }" @click="mode='duel'">⚔ <b>Дуэль техлидов</b><small>Сравните решения и рейтинг</small></button></div><div class="room-actions"><button class="btn secondary" :class="{ ready }" :disabled="!playerOnline" @click="toggleReady">{{ ready ? '✓ ГОТОВ' : 'Я ГОТОВ' }}</button><button class="btn primary" :disabled="!playerOnline || !ready" @click="start">НАЧАТЬ ИГРУ&nbsp; →</button></div></section><p v-if="error" class="online-error">{{ error }}</p><button class="back-link" @click="router.push('/')">← Вернуться в меню</button></div></template>
